spring:
  application:
    name: movieflex

  datasource:
    url: jdbc:postgresql://localhost:5432/movieflex
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
app:
    jwt:
        secret: ${JWT_SECRET_KEY:mysecretkey}
        expiration-minutes: 60


---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:h2:mem:devdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      data-locations: classpath:data-dev.sql

app:
    jwt:
        secret: Y291bnRyeWFybXljYXJyeXJvYWRleGFtaW5laGFwcGVuZWRzcGVlZGF2b2lkcmFwaWQ=
        expiration-minutes: 60

